### PR TITLE
Cache fix

### PR DESCRIPTION
**Pull request by hauxir**
Didn't mean to close the PR but I made this branch for testing out
The changes here https://github.com/hauxir/imgpush/pull/13

There's also a docker tag called hauxir/imgpush:cachefix

### CODE REVIEW

**Comment by hauxir** [comment]
I've been running this in production since yesterday and seems to be working great.

I guess the question is how you came to this fix @pdelaby ?

**Comment by pdelaby** [comment]
There was [an issue on the ImageMagick github](https://github.com/ImageMagick/ImageMagick/issues/396) , and a found [an old post of someone with a similar problem ](https://blog.bigbinary.com/2018/09/12/configuring-memory-allocation-in-imagemagick.html)
I copied the original config file from the container (shipped with imageMagick)
I am skeptical about the new values, because I randomly guessed them and I don't know what usage they fit. I'm sure they're not optimized, it needs some tests and monitoring, but it worked for me as well.

**Comment by hauxir** [comment]
Alright keep me posted! I also added an nginx server to proxy the requests recently after having some trouble with increased traffic. It seems to do wonders for performance regarding serving the files.

**Comment by hauxir** [comment]
Been running this in production for a week with no problems. Merging this.

**Pull request merged**
